### ISSUE TITLE
Garden Soil/Tilled Garden Soil

### ISSUE THREAD

**Issue by UncleSam139** [Stormwind99/CannyComposter#4]
Hi, can you add Garden Soil and Tilled Garden Soil from Garden Stuff to your mod. That would be amazing.

**Comment by Stormwind99** [comment]
We should ask @jaquadro if he is planning on porting the Garden Soil, Tilled Garden Soil, and related items from https://github.com/jaquadro/GardenStuff  to https://github.com/jaquadro/GardenCollection .

If he isn't, I'll consider it - it is cool, but I may not have the time.

**Comment by Tampa** [comment]
It has been a year now almost and no new builds or code, safe to say the original is dead. I have been putting together an update to the widely popular LifeInTheWoods pack for 1.12.2, missing various mods along with the original Garden Stuff that provided some of the most useful features of that pack. It would be nice to see the Garden Soil return as there is no equivalent mod out there that offers equal features.
